# action.yml
name: 'PHP 8.0 Lint'
description: 'PHP linter for PHP 8.0'
inputs:
  changed-files:
    description: 'changed files'
    required: true
    default: ./app/ImeeApplication.php
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.changed-files }}
