# action.yml
name: 'PHP 7.2 Lint'
description: 'PHP linter for PHP 7.2'
inputs:
  changed-files:
    description: 'changed files'
    required: true
    default: ./app/ImeeApplication.php
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.changed-files }}
